### ISSUE TITLE
Fails on windows

### ISSUE THREAD

**Issue by jantimon** [jakwings/node-temp-fs#3]
```
fs.js:758
  return binding.rmdir(pathModule._makeLong(path));
                 ^
 
Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\appveyor\AppData\Local\Temp\1\tmp-1458039469267-L2sLQ7z8tAs0'
    at Error (native)
    at Object.fs.rmdirSync (fs.js:758:18)
    at Array.unlink (C:\projects\webpack-recompilation-simulator\node_modules\temp-fs\index.js:219:14)
    at clearSync (C:\projects\webpack-recompilation-simulator\node_modules\temp-fs\index.js:86:17)
    at process.onUncaughtException (C:\projects\webpack-recompilation-simulator\node_modules\temp-fs\index.js:31:3)
    at emitOne (events.js:82:20)
    at process.emit (events.js:169:7)
    at process._fatalException (node.js:224:26)
```

Maybe you could also let your tests run on https://ci.appveyor.com/ (its travis for windows)

Full log:
https://ci.appveyor.com/project/jantimon/webpack-recompilation-simulator/build/17

Full code:
https://github.com/jantimon/webpack-recompilation-simulator/blob/308a8486bd236b394a1512a7565f5a0cac058b27/src/index.js#L37-L38

**Comment by jakwings** [comment]
I've not set up a test on windows yet, can you inspect what is inside `tmpDir`? Is `tmpFile` deleted?

**Comment by jantimon** [comment]
Unfortunately I don't have windows running here..
Just saw the tests are breaking because of the node-temp-fs plugin.

**Comment by jantimon** [comment]
Could you at least wrap it in a try - catch blog so that the module doesn't crash?

**Comment by jakwings** [comment]
This reminds me of another Windows-specific issue: isaacs/rimraf#72

still need to investigate ([VirtualBox may help](https://dev.windows.com/en-us/microsoft-edge/tools/vms/))
